# -------------
# Queries

type Query {
  user: User!
  word(id: Integer!): Word
  allWords: [Word!]!
}

# -------------
# Mutations

type Mutation {
  authGoogle(accessToken: String!): User!
  updateUser(user: UpdateUserData!): User!
  addWordDef(wordDefData: AddWordDefData!): WordData!
  addWord(wordData: AddWordData!): Word!
}

# -------------
# Types

type User {
  id: Integer!
  token: String
  email: String!
  username: String!
  createdAt: Date!
  updatedAt: Date!
  wordDefinitions: [WordData!]!
}

type Word {
  id: Integer!
  word: String!
  isPublish: Boolean!
  createdAt: Date!
  updatedAt: Date!
  wordData: [WordData!]!
  relatatedTerms: [Word!]!
  tags: [Tag!]!
}

type WordData {
  id: Integer!
  word_id: Integer!
  user_id: Integer!
  upvotes: Integer!
  definition: String!
  createdAt: Date!
  updatedAt: Date!
  word: Word!
  user: User!
}

type Tag {
  id: Integer!
  tag: String!
  createdAt: Date!
  updatedAt: Date!
  word: Word!
  relatedWord: Word!
}

# -------------
# Input types

type UpdateUserData {
  email: String
  username: String
}

type addWordDef {
  word_id: Integer!
  definition: String!
}

type AddWordData {
  word: String!
  tags: [AddWordDataTag!]
  definition: String!
}

type AddWordDataTag {
  tag: String!
}
