# -------------
# Queries

type Query {
  user: User!
  word(id: Int!): Word
  allWords: [Word!]!
}

# -------------
# Mutations

type Mutation {
  authGoogle(accessToken: String!): User!
  updateUser(user: UpdateUserData!): User!
  addWordDef(wordDefData: AddWordData!): WordData!
  addWord(wordData: AddWordDef!): Word!
}

# -------------
# Types

type User {
  id: Int!
  token: String
  email: String!
  username: String!
  createdAt: Date!
  updatedAt: Date!
  wordDefinitions: [WordData!]!
}

type Word {
  id: Int!
  word: String!
  isPublish: Boolean!
  createdAt: Date!
  updatedAt: Date!
  wordData: [WordData!]!
  relatatedTerms: [Word!]!
  tags: [Tag!]!
}

type WordData {
  id: Int!
  word_id: Int!
  user_id: Int!
  upvotes: Int!
  definition: String!
  createdAt: Date!
  updatedAt: Date!
  word: Word!
  user: User!
}

type Tag {
  id: Int!
  tag: String!
  createdAt: Date!
  updatedAt: Date!
  word: Word!
  relatedWord: Word!
}

# -------------
# Input types

input UpdateUserData {
  email: String
  username: String
}

input AddWordDef {
  word_id: Int!
  definition: String!
}

input AddWordData {
  word: String!
  tags: [AddWordDataTag!]
  definition: String!
}

input AddWordDataTag {
  tag: String!
}

# -------------
# Scalars

scalar Date
